import { Asset, AmbientCategory } from '../types';

const BASE_URL = 'https://raw.githubusercontent.com/lotanbar/zen-timer-assets/master';

function toDisplayName(id: string): string {
  return id
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function createCategorizedAmbientAsset(id: string, category: AmbientCategory): Asset {
  return {
    id,
    displayName: toDisplayName(id),
    type: 'ambient',
    category,
    audioUrl: `${BASE_URL}/ambient_by_category/${category}/audio/${id}.mp3`,
    imageUrl: `${BASE_URL}/ambient_by_category/${category}/images/${id}.jpg`,
  };
}

function createBellAsset(id: string): Asset {
  return {
    id,
    displayName: toDisplayName(id),
    type: 'bell',
    audioUrl: `${BASE_URL}/bells_audio/${id}.mp3`,
    imageUrl: `${BASE_URL}/bells_images/${id}.png`,
  };
}

// Category definitions with asset IDs
const CATEGORY_ASSETS: Record<Exclude<AmbientCategory, 'all'>, string[]> = {
  nature: [
    'active_volcano',
    'borneo_sunrise',
    'british_countryside_ambience',
    'campfire_in_the_savanna',
    'dawn_chorus_scotland',
    'desert_sounds',
    'dripping_cave',
    'dusk_in_the_country',
    'forest_campfire',
    'himalayan_dawn',
    'jungle_book_forest',
    'night_time_ambience',
    'pine_forest',
    'sardinia_by_night',
    'sounds_of_nyc',
    'storm_clouds',
    'transylvania_forest',
    'underwater_glacier',
    'wild_wind',
    'wind_through_the_trees',
    'wintery_wind',
    'woodlands_at_dawn',
  ],
  water: [
    'babbling_brook',
    'borneo_jungle',
    'calm_rain_in_the_amazon_rainforest',
    'crashing_waves',
    'dusk_by_a_stream',
    'epic_thunderstorm_in_johannesburg',
    'flowing_river',
    'fresh_spring_rain',
    'gentle_waterfall',
    'himalayan_stream',
    'island_paradise',
    'japanese_mountain_spring',
    'jungle_rain',
    'lapping_waves',
    'light_rainforest_rain',
    'monsoon_rain',
    'ocean_waves_in_madagascar',
    'pure_sound_of_rain_in_the_forest',
    'rain_and_thunder',
    'rain_and_thunder_on_lake_titicaca',
    'rain_at_dawn',
    'rainforest_rain',
    'rainforest_stream',
    'rainy_day_on_a_pacific_island',
    'rainy_morning_in_the_andes',
    'scandinavian_stream',
    'soft_rain',
    'soft_sardinian_waterfall',
    'summer_storm',
    'swedish_forest_rain',
    'windswept_beach',
  ],
  wildlife: [
    'amazon_jungle',
    'concert_of_crickets',
    'dusk_in_the_borneo_rainforest',
    'forest_mornings',
    'frogs_and_birds',
    'frogs_croaking_in_the_cloud_forest',
    'gentle_dewdrops_and_birdsong',
    'moonlight_chorus',
    'night_smyphony',
    'night_time_cicadas',
    'night_time_crickets',
    'nordic_creek_and_birds',
    'ocean_seagulls',
    'outback_sunrise',
    'singing_lyrebirds',
    'sunrise_birdcall',
    'tropical_nights',
  ],
  instrumental: [
    'balmy_evening',
    'bare_essence',
    'bubbling_flow',
    'celestial_moonlight',
    'celestial_strings',
    'celtic_serenity',
    'cherry_blossoms',
    'come_as_you_are',
    'depths_of_the_night',
    'enchanted_whispers',
    'evening_rest',
    'gaelic_dreamscapes',
    'garden_by_night',
    'gentle_evening_rain',
    'guitar_reverie',
    'homage_to_hildegard',
    'home_again_bansuri_and_ocean',
    'lullaby_bells',
    'lullaby_of_dusk',
    'moonlit_reverie',
    'morning_dawn',
    'mystical_enchantment',
    'native_american_drone_flute_with_bird_song',
    'native_american_flute_with_crickets',
    'native_american_flute_with_crystal_singing_bowl',
    'native_american_flute_with_forest_rain',
    'native_american_flute_with_piano',
    'native_american_flute_with_river_sounds',
    'patience_tree',
    'piano_dreamscape',
    'piano_echoes',
    'purifying_rain',
    'samurais_solace',
    'sanctuary_of_zen',
    'solace_in_slow_keys',
    'spring_garden',
    'sunrise_morning_bell',
    'twilight_harmony',
    'whispering_shadows',
  ],
  divine_spiritual: [
    'altered_consciousness',
    'awakening',
    'benevolent_ghosts',
    'calling_upon_the_animal_spirit',
    'centering_prayer',
    'contemplation_on_a_saint',
    'creator_of_heaven_and_earth',
    'cultivating_fire_in_the_wind',
    'drops_of_bliss',
    'finding_forgiveness',
    'finding_light_in_the_dark',
    'graceful_bliss',
    'grounding_bell_prayer',
    'mercy_from_heavens',
    'mind_cleansing',
    'morning_of_hope',
    'mother_india',
    'mystery_of_mysteries',
    'om_namah_shivaya_with_bansuri',
    'patience_prayer',
    'raga_marva',
    'refuge_In_divine_mother',
    'searching_for_the_beloved',
    'shamanic_heart',
    'spirit_invocation',
    'towards_grace',
    'towards_the_higher_worlds',
    'towards_the_underword',
    'trembling_before_the_divine',
    'yearning_and_mystery',
  ],
  frequencies_tones: [
    'bija_mantra_aum',
    'bija_mantra_ham',
    'bija_mantra_lam',
    'bija_mantra_om',
    'bija_mantra_ram',
    'bija_mantra_vam',
    'bija_mantra_yam',
    'binaural_beat_10hz',
    'binaural_beat_11hz',
    'binaural_beat_12hz',
    'binaural_beat_2hz',
    'binaural_beat_3hz',
    'binaural_beat_4hz',
    'binaural_beat_5hz',
    'binaural_beat_6hz',
    'binaural_beat_7hz',
    'binaural_beat_8hz',
    'blue_noise',
    'brown_noise',
    'crown_chakra_singing_bowl',
    'crown_drone',
    'crystal_wind_drone',
    'green_noise',
    'heart_chakra_singing_bowl',
    'infinite_om_drone',
    'monochord_drone',
    'pink_noise',
    'pythagorean_tones_108_a',
    'pythagorean_tones_135__c#',
    'pythagorean_tones_144_d',
    'pythagorean_tones_180_f#',
    'pythagorean_tones_256_c',
    'pythagorean_tones_324_e',
    'pythagorean_tones_432_a',
    'pythagorean_tones_486',
    'pythagorean_tones_g_192',
    'pythagorean_tones_g#_202.5',
    'root_chakra_singing_bowl',
    'sacral_chakra_singing_bowl',
    'solar_plexus_chakra_singing_bowl',
    'solfeggio_tones_174_hz_relieving_pain_and_stress',
    'solfeggio_tones_285_hz_healing_tissue_and_organs',
    'solfeggio_tones_396_hz_liberating_guilt_and_fear',
    'solfeggio_tones_417_hz_undoing_situations_and_facilitating_change',
    'solfeggio_tones_528_hz_transformation_and_miracles',
    'solfeggio_tones_639_hz_connecting_relationships',
    'solfeggio_tones_741_hz_awakening_intuition',
    'solfeggio_tones_852_hz_returning_to_spiritual_order',
    'solfeggio_tones_963_hz_divine_consciousness_or_enlightenment',
    'tanpura_drone',
    'third_eye_chakra_singing_bowl',
    'throat_chakra_singing_bowl',
    'white_noise',
  ],
  sound_healing: [
    'ambient_duduk',
    'ambient_native_american_flute',
    'ambient_pan_flute',
    'bansuri_and_harmonium',
    'be_here_now',
    'by_the_bubbling_brook',
    'by_the_fountain',
    'crystal_bowls',
    'crystal_singing_bowls_with_birdsong',
    'crystal_singing_bowls_with_cello',
    'crystal_singing_bowls_with_kalimba',
    'crystal_singing_bowls_with_piano',
    'crystal_singing_bowls_with_rain',
    'crystal_singing_bowls_with_steel_tongue_drum',
    'crystal_singing_bowl_with_harp',
    'didgeridoo_and_drum',
    'equanimity_in_the_rain',
    'garden_of_inner_stillness',
    'gong_bath',
    'humming',
    'idiopan',
    'koshi_chimes_earth_air',
    'koshi_chimes_earth_water',
    'koshi_chimes_fire_air',
    'koshi_chimes_water_fire',
    'koto_and_shakuhachi',
    'mystery_of_sacred_feminine',
    'passerelle',
    'rav_jam',
    'singing_bowls_with_shakuhachi',
    'soothing_guitar',
    'stillness_of_water',
    'wind_chimes',
  ],
  ambient_misc: [
    'a_major',
    'calm_waters',
    'cello_a_major',
    'cello_c_major',
    'cello_d_major',
    'cello_g_major',
    'c_major',
    'd_major',
    'forward_motion',
    'g_major',
    'horizon',
    'insights',
    'pause_and_reflect',
    'peaceful_path',
    'the_expanse',
    'warm_blanket',
  ],
};

// Generate all ambient assets from category definitions
export const AMBIENT_ASSETS: Asset[] = Object.entries(CATEGORY_ASSETS).flatMap(
  ([category, ids]) =>
    ids.map(id => createCategorizedAmbientAsset(id, category as AmbientCategory))
);

// Category labels for UI
export const AMBIENT_CATEGORIES: { id: AmbientCategory; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'nature', label: 'Nature' },
  { id: 'water', label: 'Water' },
  { id: 'wildlife', label: 'Wildlife' },
  { id: 'instrumental', label: 'Instrumental' },
  { id: 'divine_spiritual', label: 'Spiritual' },
  { id: 'frequencies_tones', label: 'Frequencies' },
  { id: 'sound_healing', label: 'Healing' },
  { id: 'ambient_misc', label: 'Misc' },
];

export const BELL_ASSETS: Asset[] = [
  'temple_bell',
  'symphonic_gong',
  'tingshas',
  'bansuri',
  'bar_chimes_rich',
  'church_bell',
  'djembe',
  'duduk',
  'flute_two_notes',
  'frame_drum_double',
  'guitar',
  'guzheng',
  'handpan',
  'harp',
  'kalimba',
  'kanun',
  'koshi_chimes_air_1',
  'koshi_chimes_earth_1',
  'koshi_chimes_fire_1',
  'koshi_chimes_water_1',
  'marimba',
  'monk',
  'native_american_flute',
  'om_mantra',
  'om_shanti_mantra',
  'oud',
  'pan_flute',
  'piano',
  'rain_stick',
  'rav_drum',
  'sarangi',
  'sarod',
  'shakuhachi',
  'sitar',
  'swinging_chimes_notes_rich',
  'tongue_drum',
  'tuning_fork',
  'turkish_ney',
  'violin',
  'vocal_hum',
  'water_gong',
  'wind_gong',
].map(createBellAsset);

export const DEFAULT_BELL_ID = 'temple_bell';

// Helper to get asset by id
export function getAssetById(id: string): Asset | undefined {
  return [...AMBIENT_ASSETS, ...BELL_ASSETS].find(a => a.id === id);
}
